swipe:
  3:
    left:
      command: "xdotool key alt+Right" # History forward
    right:
      command: "xdotool key alt+Left" # History back
    up:
      command: "xdotool key ctrl+alt+Down" # Switch to next workspace
    down:
      command: "xdotool key ctrl+alt+Up" # Switch to previous workspace
  4:
    left:
      command: "xdotool key super+Left" # View split on left
    right:
      command: "xdotool key super+Right" # # View split on right
    up:
      command: "xdotool key super+Up" # Maximize window
    down:
      command: "xdotool key super+Down" # Minimize window
pinch:
  in:
    command: "xdotool keydown ctrl click 4 keyup ctrl" # Zoom in
    threshold: 0.1
  out:
    command: "xdotool keydown ctrl click 5 keyup ctrl" # Zoom out
    threshold: 0.1

threshold:
  swipe: 0.3
  pinch: 0.3

interval:
  swipe: 0.5
  pinch: 0.5
