local o = vim.o

o.background = "dark"
o.clipboard = "unnamedplus"
o.autoindent = true
o.expandtab = true
o.softtabstop = 2
o.shiftwidth = 2
o.shiftround = true
o.splitbelow = true
o.splitright = true
o.hls = false
o.encoding = "UTF-8"
o.wrap = true
o.backspace = "indent,eol,start"
o.showbreak = "↪\\"
o.listchars = "tab:→ ,eol:↲,nbsp:␣,trail:•,extends:⟩,precedes:⟨"
o.list = true
o.updatetime = 1000
o.mouse = "a"
o.completeopt = "menu,menuone,preview,noselect,noinsert"
o.cursorline = true
o.cursorcolumn = true
o.termguicolors = true
o.number = true
o.relativenumber = true
o.laststatus = 3
o.updatetime = 250
