# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """$directory
$character"""
right_format = """$all"""

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[❯](bold green)[❯](bold red)[❯](bold yellow)"
error_symbol = "[❯](bold red)[❯](bold red)[❯](bold red)"
vimcmd_symbol = "[❮](bold green)[❮](bold red)[❮](bold yellow)"
vimcmd_replace_one_symbol = "[❮](bold purple)[❮](bold purple)[❮](bold purple)"
vimcmd_replace_symbol = "[❮](bold purple)[❮](bold purple)[❮](bold purple)"
vimcmd_visual_symbol = "[❮](bold yellow)[❮](bold yellow)[❮](bold yellow)"


[package]
disabled = true
